export const TELEGRAM_COMMANDS = [
  { command: 'help', description: 'Guide + current BirdEye/HOT/trailing rules' },
  { command: 'status', description: 'Wallet, equity, open positions, gate state' },
  { command: 'positions', description: 'Open positions + live stop/trail state' },
  { command: 'opencheck', description: 'Compare state open count vs on-chain holdings (+pending)' },
  { command: 'health', description: 'Runtime health (loop/cooldowns/provider state)' },
  { command: 'diag', description: 'Diagnostics: /diag, /diag full|momentum|confirm|execution|scanner' },
  { command: 'diagfull', description: 'Alias: /diag full (verbose diagnostics)' },
  { command: 'diagmomentum', description: 'Alias: /diag momentum (momentum-stage view)' },
  { command: 'diagconfirm', description: 'Alias: /diag confirm (confirm/attempt/fill view)' },
  { command: 'diagexecution', description: 'Alias: /diag execution (final execution-lane view)' },
  { command: 'mode', description: 'Live/paper/halted + execution toggles' },
  { command: 'config', description: 'Safe snapshot of active rules and knobs' },
  { command: 'filters', description: 'Effective liquidity/mcap/age/ratio filters' },
  { command: 'hardrejects', description: 'Show active hard reject rules' },
  { command: 'setfilter', description: 'Set filter override: liq/mcap/age/liqratio' },
  { command: 'resetfilters', description: 'Clear all filter overrides' },
  { command: 'models', description: 'Show active AI model mapping' },
  { command: 'setmodel', description: 'Set AI model for preprocess/analyze/gatekeeper' },
  { command: 'spend', description: 'Usage/cost summary (last|24h|7d|30d)' },
  { command: 'last', description: 'Show last N candidates (1..100)' },
  { command: 'candidates', description: 'Alias for /last [n]' },
  { command: 'why', description: 'Latest reject reason for symbol/mint' },
  { command: 'rejections', description: 'Reject counters by reason/source' },
  { command: 'replay', description: 'Replay presets: quick|standard|deep' },
  { command: 'optimize', description: 'Optimizer presets + override args' },
  { command: 'debug', description: 'Debug summaries on|off [mins]' },
  { command: 'pings', description: 'Throughput pings on|off' },
  { command: 'paper', description: 'Paper mode on [hours] | off' },
  { command: 'halt', description: 'Pause new entries (exits remain active)' },
  { command: 'resume', description: 'Resume new entries (re-opens runtime gate)' },
];

export function buildHelpText() {
  return [
    '🕯️ *Candle Carl Command Guide*',
    '',
    '✅ *Current live rule set*',
    '• Source hierarchy: BirdEye primary → on-chain/Jupiter secondary → Dex discovery-only',
    '• Momentum (BirdEye-native): any 2 signals + hard guards (liq≥120k, v5m≥20k, tx1h≥80, spread≤3%, age≥180s, mcap/liq≤4.5, no >10% liq drop in 60s)',
    '• Snapshot safe requires: price + liquidity + fresh(<20s); stale retries once then skip 5m',
    '• HOT queue: cold 15–30s, hot 500–1000ms, confirm 200–400ms, HOT TTL up to 10m',
    '• Trailing tiers: <30% stop@entry, 30–80%=30%, ≥80%=22%, ≥150%=18% (never widens)',
    '',
    '🚀 *Start here*',
    '• /status — wallet + equity + open count + gate',
    '• /positions — open positions + stop/trail state',
    '• /opencheck — state vs on-chain open-count reconciliation',
    '• /health — runtime loop/cooldowns/provider freshness',
    '• /diag — compact operator diagnostics',
    '• /diag full — full verbose diagnostics',
    '• /diag momentum — momentum-focused diagnostics',
    '• /diag confirm — confirm/attempt/fill-focused diagnostics',
    '• /diag execution — final execution-lane diagnostics',
    '• /diag scanner — scanner throughput + source-universe diagnostics',
    '• /diagfull /diagmomentum /diagconfirm — picker-friendly aliases',
    '• /mode — live/paper/halted + toggle posture',
    '• /config — safe snapshot of active knobs/rules',
    '',
    '🛡️ *Safety controls*',
    '• /halt  (pause new entries; exits stay active)',
    '• /resume (re-open runtime gate for entries)',
    '• /paper on [hours] | off',
    '• /pings on|off',
    '• /debug on|off [mins]',
    '',
    '📊 *Analysis / tuning*',
    '• /filters',
    '• /setfilter <liq|mcap|age|liqratio> <value>',
    '• /resetfilters',
    '• /last [n] (1..100)',
    '• /candidates [n] (alias of /last)',
    '• /why <symbol|mint>',
    '• /rejections',
    '• /spend [last|24h|7d|30d]',
    '',
    '🧰 *Advanced*',
    '• /models',
    '• /setmodel <preprocess|analyze|gatekeeper> <modelId>',
    '• /replay [quick|standard|deep] [days] [windowh=.. activate=.. distance=.. stopbuf=..]',
    '• /optimize [quick|standard|deep] [days] [top=.. windowh=.. activate=.. distance=.. stopbuf=..]',
  ].join('\n');
}
